[package]
name = "mining_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] } # Async runtime
tonic = "0.8"                                  # gRPC support
prost = "0.11"                                 # Protocol Buffers
rust-sv = { package = "sv", git = "https://github.com/murphsicles/rust-sv", tag = "v0.4.0" } # BSV-specific library
hex = "0.4"                                    # Hex decoding
toml = "0.8"                                   # Config parsing
shared = { path = "../shared" }                # Link to shared crate
block_service = { path = "../block_service" }   # For block assembly
network_service = { path = "../network_service" } # For block propagation

[build-dependencies]
tonic-build = "0.8"                            # For compiling .proto files
